#!/usr/bin/env python3
import argparse
import common

ap = argparse.ArgumentParser()
ap.add_argument("-i", required=True, 
    help="input folder of circpadtrace files to transform")
ap.add_argument("-o", required=True, 
    help="output folder for storing resulting WF files")

ap.add_argument("-t", required=False,
    help="override output filetype (.cells, .timecells, .dirtime, .pkl)")
ap.add_argument("-p", required=False, type=bool,
    help="don't store results in output, but in one pickle file")

# FIXME: consider having a noise parameter to randomize the environment 

# FIXME: we have to randomize the client traces when producing the WF output,
# because otherwise we run the risk of having time-based classifiers getting too
# accurate timings from the client ("+mikeperry | pulls: if the framework allows
# this as the default/easiest way to use it, that is what attack papers will
# use.. and then they will conclude these attacks are indefensible because
# (surprise) deep learning is able to classify pages based on CPU and memory
# usage timings on a local machine (no surprise, really)")
args = vars(ap.parse_args())

def main():
    '''Given an input folder of circpadtrace files generated by 
    torlog2circpadtrace.py, transforms them to different formats suitable for
    Website Fingerprinting (WF) classifiers. 

    Supported output formats (one of): 
    - Cells, each line only contains 1 or -1 for outgoing or incoming cells.
    - TimeCells, relative timestamp (ms) added before each cell.
    - DirectionalTime, each line has relative time multiplied with cell value.

    The Cells format is the most commonly used, while TimeCells adds time, and
    DirectionalTime is the format used by Rahman et al. in Tik-Tok.
    '''

    print("hello world")

if __name__ == "__main__":
    main()