#!/usr/bin/env python3
import argparse
import common

ap = argparse.ArgumentParser()
ap.add_argument("-i", required=True, 
    help="input folder of circpadtrace files")

ap.add_argument("-o", required=False,
    help="output file for results (JSON)")
args = vars(ap.parse_args())

def main():
    '''Given an input folder of circpadtrace files generated by 
    torlog2circpadtrace.py, computes overhead statistics.

    Bandwidth overhead is based on number of padding and non-padding cells in
    all traces. If a comparison folder of traces is given (-c argument), also
    computes statistics on relative time overheads. For time overheads to be
    reasonable, make sure the folders of traces represent the same thing (that
    is, visits to the same websites during approximately the same time and the
    same number of visits). 
    '''

    print("hello world")

if __name__ == "__main__":
    main()