#!/usr/bin/env python3
import argparse
import common

ap = argparse.ArgumentParser()
ap.add_argument("-i", required=True, 
    help="input folder of circpadtrace files to transform")
ap.add_argument("-o", required=True, 
    help="output folder for storing resulting WF files")

ap.add_argument("-t", required=False,
    help="override output filetype (.cells, .timecells, .dirtime, .pkl)")
ap.add_argument("-p", required=False, type=bool,
    help="don't store results in output, but in one pickle file")
args = vars(ap.parse_args())

def main():
    '''Given an input folder of circpadtrace files generated by 
    torlog2circpadtrace.py, transforms them to different formats suitable for
    Website Fingerprinting (WF) classifiers. 

    Supported output formats (one of): 
    - Cells, each line only contains 1 or -1 for outgoing or incoming cells.
    - TimeCells, relative timestamp (ms) added before each cell.
    - DirectionalTime, each line has relative time multiplied with cell value.

    The Cells format is the most commonly used, while TimeCells adds time, and
    DirectionalTime is the format used by Rahman et al. in Tik-Tok.
    '''

    print("hello world")

if __name__ == "__main__":
    main()